### ISSUE TITLE
As a Maker, I need to accept feedback on the bounty criteria and reward amount to make my bounty more attractive.

### ISSUE THREAD

**Issue by BitcoinBrief** [Resolvr-io/resolvr.io#12]

**Comment by ChristianChiarulli** [comment]
like a comment section?

**Comment by BitcoinBrief** [comment]
> like a comment section?

Could be a comment section.  That's not a bad idea.  I was thinking just general messaging interface.  But I like public comments (replies, essentially) at the bottom of a post.

**Comment by ChristianChiarulli** [comment]
We'll handle DMs in another issue, comment section is under the discussion tab
