### ISSUE TITLE
As a Taker, I need to filter bounties by subject area so I can apply to those I have the knowledge to solve.

### ISSUE THREAD

**Issue by BitcoinBrief** [Resolvr-io/resolvr.io#14]

**Comment by ChristianChiarulli** [comment]
we can just filter by tag here, not sure what the best way would be to present the tags yet tho.

**Comment by ChristianChiarulli** [comment]
It's difficult to do a "hard search" for things on nostr. For instance I can't ask the relay to match a word inside of the content or title. I would need to search for exact matches on things like tag. I have implemented the filter/search for bounties that are already local. Next I'll handle narrowing the search by tag.
