### ISSUE TITLE
As a Maker, I need an account to post bounties / As a Taker I need an account so I can apply for bounties.

### ISSUE THREAD

**Issue by BitcoinBrief** [Resolvr-io/resolvr.io#4]
![](https://hackmd.io/_uploads/SyrxwoRWa.png)

**Comment by BitcoinBrief** [comment]
Default should be a "Create Account" button that generates a new key pair for the user so users who aren't familiar with nostr don't need to bring their own keys.

"Login with Nostr Key" should be secondary.

Here is Snort.Social's login page...might be too busy: 
![image](https://github.com/Resolvr-io/resolvr.io/assets/115094037/1609734a-fe11-4030-b3c0-aa80aa91728a)

**Comment by ChristianChiarulli** [comment]
I think this has mostly been handled.
