### ISSUE TITLE
Display User Activity on Profile Page

### ISSUE THREAD

**Issue by BitcoinBrief** [Resolvr-io/resolvr.io#48]
The design below is just fine for alpha, let's just make it live.  

Live links to the nostr events is a want, but not a must have for alpha.

![image](https://github.com/Resolvr-io/resolvr.io/assets/115094037/bf7476ef-92e4-4922-9b5e-a7d231ee8663)

**Comment by ChristianChiarulli** [comment]
I have this mostly implemented, good enough for an alpha release.
