### ISSUE TITLE
Purge Dummy Posts/Data

### ISSUE THREAD

**Issue by BitcoinBrief** [Resolvr-io/resolvr.io#49]
For alpha public release, must purge dummy data/placeholders.

**Comment by BitcoinBrief** [comment]
"Messages" tab in the settings menu needs to go.  We aren't supporting general messaging ATM.
![Screenshot 2023-12-09 075352](https://github.com/Resolvr-io/resolvr.io/assets/115094037/20d29e5e-421e-41f6-9c8f-304dcb6ebf0c)

**Comment by Randy808** [comment]
I'll remove the messages from the menu
