### ISSUE TITLE
Remove nostrkey from localStorage

### ISSUE THREAD

**Issue by brianjcarroll** [Resolvr-io/resolvr.io#66]
In order to get NoComment to work with a Resolvr created account, we must hack it to read the key `nostrkey` from localStorage. For now, we are setting this key anywhere we are calling `setUserPrivateKey`

Search for `// https://github.com/Resolvr-io/resolvr.io/issues/66` to remove it

Also, delete public/NoComment.js

**Comment by ChristianChiarulli** [comment]
we're using next-auth and jwe cookies now
