### ISSUE TITLE
Upgrade BountyBoard UI/UX

### ISSUE THREAD

**Issue by BitcoinBrief** [Resolvr-io/resolvr.io#68]
Implement the designs from [Figma](https://www.figma.com/file/kE90JrKwu7VfetOxFXd8Q8/Resolvr-design?type=design&node-id=4%3A39&mode=design&t=FEwnq5DhReADj8dC-1) on the bounty-board site.

This will massively boost our UI scores for the hack.

**Comment by ChristianChiarulli** [comment]
@brianjcarroll we can consider this done right?

**Comment by BitcoinBrief** [comment]
Four minor tweaks I see:
1) New left side hamburger menu is duplicative of dropdown menu from user profile on the right? (also, old logo is in the left side menu and needs replacing with new logo if this second side menu is intentional):
![image](https://github.com/Resolvr-io/resolvr.io/assets/115094037/f62c4470-8690-4ed0-880c-85b6db03a812)

2) Login flow should use same font as homepage, rest of site.

3) Links to discord and GitHub next to profile icon should go to Resolvr's pages?  (this link should work: https://discord.com/invite/VRmwgV3pjP).

4) I think we default to dark mode (looks better IMO).

**Comment by Randy808** [comment]
I'll make a PR for 3 & 4. For 1 & 2 I think I need more context
