### ISSUE TITLE
Read From multiple relays

### ISSUE THREAD

**Issue by BitcoinBrief** [Resolvr-io/resolvr.io#73]
Because the webclient is only reading from one relay at a time, it's not displaying full information on profiles and bounties.

Change default to read from multiple relays.

**Comment by ChristianChiarulli** [comment]
I don't think I'll have this done for the hackathon, I'll need to do a deeper rewrite for much of the relay logic. The good news is I have this working on another app so we will eventually be able to get it working here as well.

**Comment by ChristianChiarulli** [comment]
This is now implemented
