### ISSUE TITLE
As a Maker, I need to create a public post so I can advertise my bounty to potential takers.

### ISSUE THREAD

**Issue by BitcoinBrief** [Resolvr-io/resolvr.io#8]
![](https://hackmd.io/_uploads/rJ6ZdsR-p.png)

**Comment by ChristianChiarulli** [comment]
We need to further flesh out the create page and make sure the user zaps the event, only events with zap receipts should show on the bounty page.

**Comment by BitcoinBrief** [comment]
Zap-to-post bounty feature will be good anti-spam feature, but might need to wait until core bounty lifecycle is completed.

**Comment by ChristianChiarulli** [comment]
We're routing directly to the bounty after creation now, let me know what you think.

**Comment by BitcoinBrief** [comment]
> We're routing directly to the bounty after creation now, let me know what you think.

Bounty creation button is not routing me to bounty when I click create.
