### ISSUE TITLE
As a Maker, I need to provide detailed criteria for a successful bounty so the taker can create the solution I want.  As a Maker, I need to provide detailed criteria for a successful bounty so only those takers who are qualified to perform the work will take it.

### ISSUE THREAD

**Issue by BitcoinBrief** [Resolvr-io/resolvr.io#9]

**Comment by ChristianChiarulli** [comment]
Right now I'm doing something similar to how replit does it:

![image](https://github.com/Resolvr-io/resolvr.io/assets/29136904/b8703909-32f2-4a6a-b9cb-0588074e2d52)

Do you have something else in mind?

**Comment by BitcoinBrief** [comment]
I like the fee breakdown right up front.  And instead of "buy 150k cycles" a button that says "Fund Bounty" (which will bring up the dialog box flow for inputting escrow transaction details).  Don't need the "communication method" - messaging built in with nostr.

**Comment by ChristianChiarulli** [comment]
I agree, I think we have the ability to provide detailed bounties, I think being able to fund the bounty should be a separate issue.
